# Generated by Django 3.2.5 on 2021-08-02 12:50

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='アルバム名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='ファイル名')),
                ('hash', models.CharField(max_length=256, verbose_name='ファイルハッシュ')),
                ('mime', models.CharField(max_length=256, verbose_name='ファイル種別')),
                ('suffix', models.CharField(max_length=256, verbose_name='ファイル拡張子')),
                ('option', models.JSONField(verbose_name='オプション')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumFile',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=256, verbose_name='アルバム内ファイル名')),
                ('ordering', models.IntegerField(default=128, verbose_name='表示順')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.album', verbose_name='アルバム')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.file', verbose_name='ファイル')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='album',
            name='files',
            field=models.ManyToManyField(through='main.AlbumFile', to='main.File', verbose_name='ファイル'),
        ),
    ]
